common:
    lid_topic:  "/camera/depth/color/points"
    imu_topic:  "/camera/imu"
#    imu_topic:  "/livox/imu"

preprocess:
    lidar_type: 4                # Realsense L515
    feature_extract_en: false
    scan_line: 6
    blind: 1
    
calibration:
    orig_odom_freq: 30
    mean_acc_norm: 9.81 # 1: for livox built-in IMU
    online_refine_time: 30.0
    data_accum_length: 100

mapping:
    imu_en: false
    filter_size_surf: 0.05
    filter_size_map: 0.15
    acc_cov: 10
    gyr_cov: 2
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    det_range:     10.0
    extrinsic_T: [ 0.0, 0.0, 0.0 ]
    extrinsic_R: [ 1, 0, 0,
                   0, 1, 0,
                   0, 0, 1]

publish:
    path_en:  true
    scan_publish_en:  true       # false: close all the point cloud output
    dense_publish_en: true       # false: low down the points number in a global-frame point clouds scan.
    scan_bodyframe_pub_en: true  # true: output the point cloud scans in IMU-body-frame

pcd_save:
    pcd_save_en: false
    interval: -1                 # how many LiDAR frames saved in each pcd file; 
                                 # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
